# Generated by Django 5.2.6 on 2025-10-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store1', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
